### ISSUE TITLE
How can switch automatically send request to controller at a fixed rate?

### ISSUE THREAD

**Issue by minziran** [onosproject/onos-topo#145]
In my simulation, I assume switch can send requests to ONOS controller at a fixed rate. Is there any ONOS application that can do that? Or is there any software that can help me? If not, the worst case is generating requests from the host side, correct?

Thanks!

**Comment by adibrastegarnia** [comment]
@minziran 
I would suggest to join onosproject slack (https://slackin.onosproject.org/)  ask your question in general channel there. This repo is related to micro-onos. I hope it helps. I will close the issue
