### ISSUE TITLE
Topology Destruction

### ISSUE THREAD

**Issue by AneeqAbid06** [onosproject/onos-topo#205]
Hi,

I ran the following command to create a test MININET Optical topology in ONOS and now it won't let me destroy the topology.

sudo -E python onos/tools/test/topos/opticalTestBig.py

Running the command "wipe-out please" in ONOS deletes the topology but it immediately reappears. What do I do?

**Comment by adibrastegarnia** [comment]
@AneeqAbid06 
This repo is related to micro-onos project  but it seems your question is related to ONOS classic (https://github.com/opennetworkinglab/onos). I would suggest to ask your question in onos development mailing list. 
https://wiki.onosproject.org/display/ONOS/Mailing+Lists

**Comment by AneeqAbid06** [comment]
@adibrastegarnia 
Thank you for your response. I will hop to the recommended relevant group.
