### ISSUE TITLE
handler for onos-topo DeviceService/List with subscribe should handle client disconnect

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-topo#27]
In the file 
https://github.com/onosproject/onos-topo/blob/master/pkg/northbound/device/service.go line 99
the handler does not handle a client disconnect, and stays running

This might become a problem when the onos-gui is attached, as the client disconnects when the user browses away from the topology page.

I found this was necessary with the GetOpState and used a mechanism to handle **<-stream.Context().Done()**. See:
https://github.com/onosproject/onos-config/blob/master/pkg/northbound/diags/diags.go line 183 
that handles this.

**Comment by adibrastegarnia** [comment]
@SeanCondon @kuujo 
Is this resolved?

**Comment by kuujo** [comment]
Not yet. We need to update the Atomix client, because this issue goes all the way through to the Atomix servers as well. The Atomix client now supports closing streams from the client side, but it needs to be implemented in the DeviceService here.
