### ISSUE TITLE
Move proto files/code to standalone package

### ISSUE THREAD

**Issue by kuujo** [onosproject/onos-topo#49]
In onos-config we created a separate package for protobuf files/code. This works well because the generated code doesn’t count against test coverage. It also allows other subsystems to import Protobuf types without importing implementations (e.g. services/stores), which can create dependency conflicts: We need to do the same for topo northbound APIs.

My proposal is to create a convention in which we separate serializable types into two packages:
* Public API - types that are exposed via a northbound API and can be imported by other services
* Private API - types that are stored e.g. in databases but not exposed via a northbound API

The public API needs to be separate from the subsystem’s code - maybe just in a top level `api` Or `proto` package.

**Comment by Andrea-Campanella** [comment]
#50 fixes this
